server:
  port: 15410
spring:
  application:
    name: key-control
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          url-expression: "'lb:http://'+serviceId"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/topazkeys?ApplicationName=Key-Control
    username: topaz
    password: office
    hikari:
      maximum-pool-size: 3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false
liquibase:
  enable: true
springdoc:
  swagger-ui:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.243:8761/eureka/